name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        version:
          - "3.16.1"
          - "3.16.0"
        os:
          - "ubuntu-22.04"
          - "ubuntu-20.04"
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update apt index
        run: sudo apt update -y -qq
      - name: Install dependency packages
        run: |
          sudo apt install -y -qq --no-install-recommends \
                build-essential \
                bison \
                flex \
                libssl-dev \
                pkg-config \
                libpcre3-dev \
                libwww-perl \
                libgnutls28-dev
      - name: Build Inspircd ${{matrix.version}}
        run: bash install.sh ${{matrix.version}}
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - name: Archive build artifacts
        run: tar cvzf inspircd.${{matrix.version}}.${{matrix.os}}.tar.gz run/
      - name: Upload archives
        uses: actions/upload-artifact@v4
        with:
          name: inspircd.${{matrix.version}}.${{matrix.os}}.tar.gz
          path: inspircd*.tar.gz
          if-no-files-found: error
