name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        version:
          - "3.16.1"
          - "3.16.0"
        os:
          - "ubuntu-22.04"
          - "ubuntu-20.04"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update -y -qq
      - run: |
          sudo apt install -y -qq --no-install-recommends \
                build-essential \
                bison \
                flex \
                libssl-dev \
                pkg-config \
                libpcre3-dev \
                libwww-perl \
                libgnutls28-dev
      - run: bash install.sh ${{ matrix.version }}
      - id: commit
        uses: prompt/actions-commit-hash@v3
      - run: tar cvzf inspircd.${{matrix.version}}-${{steps.commit.outputs.short}}.${{matrix.os}}.tar.gz run/
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: inspircd*.tar.gz
