name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt update -y -qq
      - run: |
          sudo apt install -y -qq --no-install-recommends \
                build-essential \
                bison \
                flex \
                libssl-dev \
                pkg-config \
                libpcre3-dev \
                libwww-perl \
                libgnutls28-dev
      - run: bash install.sh
      - run: tar cvzf inspircd.tar.gz run/
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: inspircd.tar.gz
